[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "flake8_sphinx_links"
version = "0.1.0"
description = "A Flake8 plugin to check docstrings for double backticked strings which should be links to the Python documentation."
readme = "README.rst"
keywords = [ "flake8", "sphinx", "documentation",]
dynamic = [ "requires-python", "classifiers", "dependencies",]
[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/flake8-sphinx-links"
"Issue Tracker" = "https://github.com/domdfcoding/flake8-sphinx-links/issues"
"Source Code" = "https://github.com/domdfcoding/flake8-sphinx-links"
Documentation = "https://flake8-sphinx-links.readthedocs.io/en/latest"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Flake8",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython", "PyPy",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"

[project.entry-points."flake8.extension"]
SXL = "flake8_sphinx_links:Plugin"
